print(" Hey ")
print(" Damaris Muthoni, That's my name  ")
print(" Why I am Learning python")
print(" To add skills to my Data Scientist Path")
print(" The Bast thing about programing")
print(" Is that I can Channel my creative side through code")
print(" Today is day 4 of code")
print(" I dedicate myself to learn and perfect")
print(" My skills ")
print(" And Master Python")
